variable "aws_region" {}
variable "aws_profile" {}
variable ami {}
variable instance_type {}
variable subnetid {}
variable count {}
variable iaminstanceprofile {} 
variable availabilityzone {}
variable aws_security_group1 {}
variable aws_security_group2 {}
variable aws_security_group3 {}
variable key_pair_name {}
variable volume_size {}
variable name {}
variable env {}
variable projectname {}
variable ssm {}
variable server {}
variable today {}
variable metric_name {}
variable costgroup {}
variable aws_sns_topic_arn {}